import type { CompetitorDashboardAccount } from "@/types/competitorDashboard";

export const competitorDashboardAccounts: CompetitorDashboardAccount[] = [
  {
    id: "walmart",
    rank: 1,
    customerName: "Walmart",
    channel: "Retail",
    coverage: "direct-public",
    trackingEntity: "Walmart",
    ticker: "WMT",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Thu May 21, 2026 — pre-market. Confirm once Walmart IR posts the agenda.",
    nextReleaseDate: "2026-05-21",
    flashStatus: "ready-to-draft",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Highest priority packaged meats account. AlphaSense summary should be same-day.",
  },
  {
    id: "kroger",
    rank: 2,
    customerName: "Kroger",
    channel: "Retail",
    coverage: "direct-public",
    trackingEntity: "Kroger",
    ticker: "KR",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Thu Jun 18, 2026 — pre-market, based on prior-year cadence.",
    nextReleaseDate: "2026-06-18",
    flashStatus: "monitoring",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Track guidance commentary around category traffic and pricing.",
  },
  {
    id: "sysco",
    rank: 3,
    customerName: "Sysco",
    channel: "Foodservice",
    coverage: "direct-public",
    trackingEntity: "Sysco",
    ticker: "SYY",
    releaseStatus: "needs-date",
    nextReleaseLabel: "Need next earnings date from Sysco IR calendar.",
    flashStatus: "not-started",
    flashReportRequired: true,
    owner: "Jeff",
    notes: "Foodservice volume and mix comments matter for downstream demand framing.",
  },
  {
    id: "alb-sfwy",
    rank: 6,
    customerName: "ALB/SFWY",
    channel: "Retail",
    coverage: "direct-public",
    trackingEntity: "Albertsons",
    ticker: "ACI",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Wed Jul 15, 2026 — pre-market, based on prior-year window.",
    nextReleaseDate: "2026-07-15",
    flashStatus: "monitoring",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Parent ticker covers the Albertsons / Safeway footprint.",
  },
  {
    id: "us-foods",
    rank: 7,
    customerName: "US Foods",
    channel: "Foodservice",
    coverage: "direct-public",
    trackingEntity: "US Foods",
    ticker: "USFD",
    releaseStatus: "needs-date",
    nextReleaseLabel: "Need date and webcast link from US Foods IR.",
    flashStatus: "not-started",
    flashReportRequired: true,
    owner: "Jeff",
    notes: "Monitor independent restaurant momentum and volume outlook.",
  },
  {
    id: "costco",
    rank: 8,
    customerName: "Costco",
    channel: "Club",
    coverage: "direct-public",
    trackingEntity: "Costco",
    ticker: "COST",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Thu May 28, 2026 — after-hours. Monthly sales updates may pre-signal results.",
    nextReleaseDate: "2026-05-28",
    flashStatus: "ready-to-draft",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Include any commentary on fresh traffic and membership renewal strength.",
  },
  {
    id: "pfg",
    rank: 9,
    customerName: "PFG",
    channel: "Foodservice",
    coverage: "direct-public",
    trackingEntity: "Performance Food Group",
    ticker: "PFGC",
    releaseStatus: "needs-date",
    nextReleaseLabel: "Need PFG earnings date before flash workflow can be queued.",
    flashStatus: "not-started",
    flashReportRequired: true,
    owner: "Jeff",
    notes: "Watch independent operator demand and case growth.",
  },
  {
    id: "dollar-general",
    rank: 10,
    customerName: "Dollar General",
    channel: "Retail",
    coverage: "direct-public",
    trackingEntity: "Dollar General",
    ticker: "DG",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Thu May 28, 2026 — pre-market. Verify from DG events page.",
    nextReleaseDate: "2026-05-28",
    flashStatus: "monitoring",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Low-income traffic and value-channel commentary should be highlighted.",
  },
  {
    id: "unfi",
    rank: 14,
    customerName: "UNFI",
    channel: "Distribution",
    coverage: "direct-public",
    trackingEntity: "UNFI",
    ticker: "UNFI",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Tue Jun 9, 2026 — after-hours. Confirm once UNFI posts materials.",
    nextReleaseDate: "2026-06-09",
    flashStatus: "monitoring",
    flashReportRequired: true,
    owner: "Jeff",
    notes: "Important wholesale read-through for grocery and natural channels.",
  },
  {
    id: "mcdonalds",
    rank: 20,
    customerName: "McDonalds",
    channel: "QSR",
    coverage: "direct-public",
    trackingEntity: "McDonald's",
    ticker: "MCD",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Tue Jul 28, 2026 — pre-market. Verify once MCD events page refreshes.",
    nextReleaseDate: "2026-07-28",
    flashStatus: "ready-to-draft",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Useful food-away-from-home demand read-through for protein traffic.",
  },
  {
    id: "bjs",
    rank: 23,
    customerName: "BJs",
    channel: "Club",
    coverage: "direct-public",
    trackingEntity: "BJ's Wholesale Club",
    ticker: "BJ",
    releaseStatus: "estimated",
    nextReleaseLabel: "Estimated Thu May 21, 2026 — pre-market. Calendar source still pending.",
    nextReleaseDate: "2026-05-21",
    flashStatus: "monitoring",
    flashReportRequired: true,
    owner: "Tri",
    notes: "Club-channel comp trends make this worth a quick same-day note.",
  },
];
